kind: pipeline
steps:
- name: Install
  image: maven:3-jdk-11
  commands:
  - mvn clean install
  
- name: Package-master
  image: maven:3-jdk-11
  commands:
  - mvn clean package
  when:
    branch:
      - master
